import Link from "next/link";
import "../globals.css";
import { Inter } from "next/font/google";
import { getPages } from "@/sanity/sanity-utils";
import SchoolIcon from '@mui/icons-material/School';
import ContactMailIcon from '@mui/icons-material/ContactMail';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Galleria Technologica",
  description: "Generated by Nextjs + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all our pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className={inter.className + "mx-auto pt-10 px-5"}>
        <header className="lg:px-10 flex items-center justify-between">
          <Link
            href="/"
            className="pb-4 text-lg md:text-5xl lg:text-6xl bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent font-bold"
          >
            Galleria Tecnologica
          </Link>
          <div className="flex items-center gap-5 text-sm text-grey-600">
            {/* {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="hover:underline">
                {page.title}
              </Link>
            ))} */}
            <Link href='/about' className="hover:underline">
              <SchoolIcon />
            </Link>
            <Link href='/contact' className="hover:underline">
              <ContactMailIcon />
            </Link>
          </div>
        </header>
        <main className="lg:px-10"> {children}</main>
      </body>
    </html>
  );
}
